version: "3"
services:
  mongo:
    container_name: test-mongo
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=spider
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"